### ISSUE TITLE
アニメーションについて

### ISSUE THREAD

**Issue by nonchy-83** [WaffleCollege/team-i#16]
questionpage.html上の、swipe upの矢印がある、question-textクラスを、上下にbounceさせるアニメーションをつけたいと考えてる。

迷っていること

- CSSアニメーション？
- js使ったアニメーション？

**Comment by marimotona** [comment]
のんちゃんが好きな方とか、、？？
もし、JSでのアニメーションに挑戦したかったら、JSでもよいと思うけど、
全体を通して、アニメーションはＪＳでやるみたいな感じで統一できると、
後々混乱しなそう！

**Comment by marimotona** [comment]
のんちゃんが好きな方とか、、？？
もし、JSでのアニメーションに挑戦したかったら、JSでもよいと思うけど、
全体を通して、アニメーションはＪＳでやるみたいな感じで統一できると、
後々混乱しなそう！

**Comment by nonchy-83** [comment]
アニメーションは、jsでやるのに統一したいと思った！
jQueryを使う方向でいきたいのだが、jQueryにあまり自信がないから、progateで半日くらいjQueryさわってからアニメーションつけていくね。

**Comment by marimotona** [comment]
おけーー！了解！
